#!/usr/bin/env bash
#
# Build versions.json v2 by inspecting release artifacts in GCS for this tag
# and every prior tag. Emits checksums + sizes per platform per component,
# and a `delta` pointer where applicable (delta artifacts themselves are
# generated by a sibling cloudbuild step in Sprint 4 — this script just
# references them if they exist).
#
# Env in (set by cloudbuild.yaml substitutions):
#   _BUCKET        — GCS bucket name
#   _TAG_NAME      — current release tag (e.g. v1.0.3)
#   _EXPORT_NAME   — Godot export base filename
#
# Output:
#   ./versions.json   — manifest v2 written to current dir; caller uploads it.
#
# This script assumes the upload-release step has already placed the new
# release's artifacts at gs://$_BUCKET/releases/$_TAG_NAME/.

set -euo pipefail

: "${_BUCKET:?must be set}"
: "${_TAG_NAME:?must be set}"
: "${_EXPORT_NAME:?must be set}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

base_url="https://storage.googleapis.com/${_BUCKET}/releases"

# ─── List every released version (tag) under releases/ ───────────────────────
versions=$(gsutil ls "gs://${_BUCKET}/releases/" 2>/dev/null \
  | sed -nE 's#^gs://[^/]+/releases/(v[0-9].*)/$#\1#p' \
  | sort -V)

if ! echo "$versions" | grep -qx "${_TAG_NAME}"; then
  versions="${versions}
${_TAG_NAME}"
fi

# Newest first, for the `latest` field.
latest=$(echo "$versions" | sort -V | tail -1)

# Component definitions per platform.
# Each line: platform|component|gcs_path_template|installed_name
# {tag} placeholder gets substituted per-version below.
component_table=$(cat <<'EOF'
windows|launcher|launcher/{tag}/windows/launcher.exe|launcher.exe
windows|game_binary|releases/{tag}/windows.zip|battle-royale.exe
windows|rust_lib|rust-libs/{tag}/rust.dll|rust.dll
windows|pck_base|releases/{tag}/windows-base.pck|battle-royale.pck
windows|pck_patch|releases/{tag}/windows-{tag}.pck|windows-{tag}.pck
linux|launcher|launcher/{tag}/linux/launcher|launcher
linux|game_binary|releases/{tag}/linux.zip|battle-royale.x86_64
linux|rust_lib|rust-libs/{tag}/librust.so|librust.so
linux|pck_base|releases/{tag}/linux-base.pck|battle-royale.pck
linux|pck_patch|releases/{tag}/linux-{tag}.pck|linux-{tag}.pck
mac|launcher|launcher/{tag}/mac/launcher|launcher
mac|game_binary|releases/{tag}/mac.zip|battle-royale
mac|rust_lib|rust-libs/{tag}/librust.dylib|librust.dylib
mac|pck_base|releases/{tag}/mac-base.pck|battle-royale.pck
mac|pck_patch|releases/{tag}/mac-{tag}.pck|mac-{tag}.pck
EOF
)

# ─── For each version × platform × component: stat object, get size + sha256 ─
# We compute sha256 by streaming the object through sha256sum once. GCS
# doesn't expose ed25519 / sha256 metadata by default; the CRC32C and MD5
# it returns aren't what we want. So download to a temp file.
declare -A blob_sha
declare -A blob_size
declare -A blob_url

get_blob_info() {
  local gcs_path="$1"
  local cache_key="$gcs_path"
  if [[ -n "${blob_sha[$cache_key]:-}" ]]; then
    return 0
  fi
  if ! gsutil -q stat "gs://${_BUCKET}/${gcs_path}" >/dev/null 2>&1; then
    return 1
  fi
  local tmp="${WORK}/blob.$(echo "$gcs_path" | tr '/' '_')"
  gsutil -q cp "gs://${_BUCKET}/${gcs_path}" "$tmp"
  blob_sha[$cache_key]=$(sha256sum "$tmp" | awk '{print $1}')
  blob_size[$cache_key]=$(stat -c%s "$tmp" 2>/dev/null || stat -f%z "$tmp")
  blob_url[$cache_key]="https://storage.googleapis.com/${_BUCKET}/${gcs_path}"
  rm -f "$tmp"
}

# ─── Build the JSON ──────────────────────────────────────────────────────────
# Stream out to versions.json via jq. We construct a nested map and let jq
# pretty-print at the end.

jq_input=$(jq -n '{schema: 2, latest: $latest, versions: {}}' --arg latest "$latest")

prev_tag=""
for tag in $(echo "$versions" | sort -V); do
  # For historical versions, read released_at from GCS object creation time of
  # the canonical base PCK so we don't overwrite past timestamps on every
  # rebuild. For the current tag, use now.
  if [[ "$tag" == "${_TAG_NAME}" ]]; then
    released_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  else
    # Pick any base PCK as the representative artifact; fall through to "now"
    # if absent (shouldn't happen for an indexed version).
    released_at=$(gsutil stat "gs://${_BUCKET}/releases/${tag}/linux-base.pck" 2>/dev/null \
      | awk -F': ' '/Creation time:/ {print $2}' \
      | xargs -I{} date -u -d '{}' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null) \
      || released_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  fi
  version_obj='{released_at: $rel, platforms: {}}'
  jq_input=$(echo "$jq_input" | jq --arg tag "$tag" --arg rel "$released_at" \
    ".versions[\$tag] = $version_obj")

  while IFS='|' read -r platform component path_tpl installed_name; do
    [[ -z "$platform" ]] && continue
    full_path=${path_tpl//\{tag\}/$tag}
    if ! get_blob_info "$full_path"; then
      continue
    fi
    sha=${blob_sha[$full_path]}
    size=${blob_size[$full_path]}
    url=${blob_url[$full_path]}

    component_json=$(jq -n \
      --arg url "$url" --arg sha "$sha" --argjson size "$size" \
      --arg installed_name "$installed_name" \
      '{url: $url, sha256: $sha, size: $size, installed_name: $installed_name}')

    # Optional delta block (populated by Sprint 4 step).
    if [[ "$component" != "pck_base" && "$component" != "pck_patch" && -n "$prev_tag" ]]; then
      delta_path="deltas/${tag}/${platform}/${component}.zpatch"
      if get_blob_info "$delta_path" 2>/dev/null; then
        delta_json=$(jq -n \
          --arg url "${blob_url[$delta_path]}" \
          --arg sha "${blob_sha[$delta_path]}" \
          --argjson size "${blob_size[$delta_path]}" \
          --arg from "$prev_tag" \
          '{url: $url, sha256: $sha, size: $size, from: $from, algo: "zstd"}')
        component_json=$(echo "$component_json" | jq --argjson d "$delta_json" '. + {delta: $d}')
      fi
    fi

    jq_input=$(echo "$jq_input" | jq \
      --arg tag "$tag" --arg platform "$platform" --arg component "$component" \
      --argjson c "$component_json" \
      '.versions[$tag].platforms[$platform][$component] = $c')
  done <<< "$component_table"

  prev_tag="$tag"
done

echo "$jq_input" | jq '.' > versions.json
echo "Wrote versions.json ($(wc -c < versions.json) bytes)"
