#!/usr/bin/env bash
#
# Build versions.json v2 by inspecting release artifacts in GCS for this tag
# and every prior tag. Emits checksums + sizes per platform per component,
# and a `delta` pointer where applicable (delta artifacts themselves are
# generated by a sibling cloudbuild step in Sprint 4 — this script just
# references them if they exist).
#
# Env in (set by cloudbuild.yaml substitutions):
#   _BUCKET        — GCS bucket name
#   _TAG_NAME      — current release tag (e.g. v1.0.3)
#   _EXPORT_NAME   — Godot export base filename
#
# Output:
#   ./versions.json   — manifest v2 written to current dir; caller uploads it.
#
# This script assumes the upload-release step has already placed the new
# release's artifacts at gs://$_BUCKET/releases/$_TAG_NAME/.

set -euo pipefail

: "${_BUCKET:?must be set}"
: "${_TAG_NAME:?must be set}"
: "${_EXPORT_NAME:?must be set}"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

base_url="https://storage.googleapis.com/${_BUCKET}/releases"

# ─── List every released version (tag) under releases/ ───────────────────────
versions=$(gsutil ls "gs://${_BUCKET}/releases/" 2>/dev/null \
  | sed -nE 's#^gs://[^/]+/releases/(v[0-9].*)/$#\1#p' \
  | sort -V)

if ! echo "$versions" | grep -qx "${_TAG_NAME}"; then
  versions="${versions}
${_TAG_NAME}"
fi

# Newest first, for the `latest` field.
latest=$(echo "$versions" | sort -V | tail -1)

# Component definitions per platform.
# Each line: platform|component|gcs_path_template|installed_name
# {tag} placeholder gets substituted per-version below.
component_table=$(cat <<'EOF'
windows|launcher|launcher/{tag}/windows/launcher.exe|launcher.exe
windows|launcher_updater|launcher/{tag}/windows/launcher-updater.exe|launcher-updater.exe
windows|game_binary|releases/{tag}/windows.zip|battle-royale.exe
windows|rust_lib|rust-libs/{tag}/rust.dll|rust.dll
windows|pck_base|releases/{tag}/windows-base.pck|battle-royale.pck
linux|launcher|launcher/{tag}/linux/launcher|launcher
linux|launcher_updater|launcher/{tag}/linux/launcher-updater|launcher-updater
# Linux's game_binary points at the standalone binary (not the full linux.zip
# that windows/mac entries reference) so the dedicated-server VM can apply
# atomic per-file updates via launcher --update-only — no 1+ GB zip extract
# in systemd's ExecStartPre window. See cloudbuild.yaml's zip-builds step.
linux|game_binary|releases/{tag}/linux-battle-royale.x86_64|battle-royale.x86_64
linux|rust_lib|rust-libs/{tag}/librust.so|librust.so
linux|pck_base|releases/{tag}/linux-base.pck|battle-royale.pck
mac|launcher|launcher/{tag}/mac/launcher|launcher
mac|launcher_updater|launcher/{tag}/mac/launcher-updater|launcher-updater
mac|game_binary|releases/{tag}/mac.zip|battle-royale
mac|rust_lib|rust-libs/{tag}/librust.dylib|librust.dylib
mac|pck_base|releases/{tag}/mac-base.pck|battle-royale.pck
EOF
)

# ─── For each version × platform × component: stat object, get size + sha256 ─
# We compute sha256 by streaming the object through sha256sum once. GCS
# doesn't expose ed25519 / sha256 metadata by default; the CRC32C and MD5
# it returns aren't what we want. So download to a temp file.
declare -A blob_sha
declare -A blob_size
declare -A blob_url

get_blob_info() {
  local gcs_path="$1"
  local cache_key="$gcs_path"
  if [[ -n "${blob_sha[$cache_key]:-}" ]]; then
    return 0
  fi
  if ! gsutil -q stat "gs://${_BUCKET}/${gcs_path}" >/dev/null 2>&1; then
    return 1
  fi
  local tmp="${WORK}/blob.$(echo "$gcs_path" | tr '/' '_')"
  gsutil -q cp "gs://${_BUCKET}/${gcs_path}" "$tmp"
  blob_sha[$cache_key]=$(sha256sum "$tmp" | awk '{print $1}')
  blob_size[$cache_key]=$(stat -c%s "$tmp" 2>/dev/null || stat -f%z "$tmp")
  blob_url[$cache_key]="https://storage.googleapis.com/${_BUCKET}/${gcs_path}"
  rm -f "$tmp"
}

# ─── Build the JSON ──────────────────────────────────────────────────────────
# Strategy: pull the previously-published manifest (if any) and reuse its
# version entries verbatim. Only re-hash artifacts for the CURRENT tag. This
# keeps generate-manifest O(1) per release instead of O(num_releases).
#
# Cold-build fallback: if no prior manifest exists OR its schema is wrong,
# emit a fresh manifest containing only the current tag (historical tags
# would have been published with the legacy v1 schema and aren't recoverable
# without a re-hash — operator can backfill manually if needed).

prior_path="$WORK/prior.json"
if gsutil -q cp "gs://${_BUCKET}/versions.json" "$prior_path" 2>/dev/null; then
  prior_schema=$(jq -r '.schema // 0' "$prior_path" 2>/dev/null || echo 0)
  if [[ "$prior_schema" == "2" ]]; then
    jq_input=$(jq --arg latest "$latest" '.latest = $latest' "$prior_path")
    echo "Reusing $(jq '.versions | length' "$prior_path") prior version entries from published manifest."
  else
    echo "Prior manifest schema=$prior_schema, not v2 — building fresh."
    jq_input=$(jq -n '{schema: 2, latest: $latest, versions: {}}' --arg latest "$latest")
  fi
else
  echo "No prior versions.json on GCS — building fresh."
  jq_input=$(jq -n '{schema: 2, latest: $latest, versions: {}}' --arg latest "$latest")
fi

# Previous tag (used for delta `from:` field). Take the highest version
# strictly less than _TAG_NAME from the bucket listing.
prev_tag=$(echo "$versions" | grep -vx "${_TAG_NAME}" | sort -V | tail -1 || true)

# Only hash artifacts for the CURRENT release. Historical entries come from
# the prior manifest above.
tag="${_TAG_NAME}"
released_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
# Cross-platform build identity for this release. Written to release/BUILD_SHA
# by the compute-build-sha + zip-builds cloudbuild steps. The launcher reads
# this from the manifest and stamps build-sha.txt next to the game binary on
# every update — keeps the in-game version handshake aligned with the
# actually-installed release without having to re-download the platform zip.
if [[ -f release/BUILD_SHA ]]; then
  current_build_sha=$(cat release/BUILD_SHA)
else
  echo "WARNING: release/BUILD_SHA missing — manifest will omit build_sha for $tag" >&2
  current_build_sha=""
fi
version_obj='{released_at: $rel, build_sha: $build_sha, platforms: {}}'
jq_input=$(echo "$jq_input" | jq --arg tag "$tag" --arg rel "$released_at" \
  --arg build_sha "$current_build_sha" \
  ".versions[\$tag] = $version_obj")

while IFS='|' read -r platform component path_tpl installed_name; do
  [[ -z "$platform" ]] && continue
  full_path=${path_tpl//\{tag\}/$tag}
  # installed_name may legitimately contain {tag} for future components — leave
  # the substitution in place so a literal "{tag}" never leaks into the
  # manifest and confuses the launcher's atomic-rename path.
  installed_name=${installed_name//\{tag\}/$tag}
  if ! get_blob_info "$full_path"; then
    continue
  fi
  sha=${blob_sha[$full_path]}
  size=${blob_size[$full_path]}
  url=${blob_url[$full_path]}

  component_json=$(jq -n \
    --arg url "$url" --arg sha "$sha" --argjson size "$size" \
    --arg installed_name "$installed_name" \
    '{url: $url, sha256: $sha, size: $size, installed_name: $installed_name}')

  # Optional delta block. Every component supports zstd deltas now that
  # pck_patch is gone — pck_base in particular is the dominant payload and
  # benefits the most.
  if [[ -n "$prev_tag" ]]; then
    delta_path="deltas/${tag}/${platform}/${component}.zpatch"
    if get_blob_info "$delta_path" 2>/dev/null; then
      delta_json=$(jq -n \
        --arg url "${blob_url[$delta_path]}" \
        --arg sha "${blob_sha[$delta_path]}" \
        --argjson size "${blob_size[$delta_path]}" \
        --arg from "$prev_tag" \
        '{url: $url, sha256: $sha, size: $size, from: $from, algo: "zstd"}')
      component_json=$(echo "$component_json" | jq --argjson d "$delta_json" '. + {delta: $d}')
    fi
  fi

  jq_input=$(echo "$jq_input" | jq \
    --arg tag "$tag" --arg platform "$platform" --arg component "$component" \
    --argjson c "$component_json" \
    '.versions[$tag].platforms[$platform][$component] = $c')
done <<< "$component_table"

echo "$jq_input" | jq '.' > versions.json
echo "Wrote versions.json ($(wc -c < versions.json) bytes, $(jq '.versions | length' versions.json) versions)"
