// Public key embedded at compile time. Generated by
// infrastructure/keys/generate-signing-key.sh and committed to the repo at
// infrastructure/keys/manifest_pub.ed25519 (32 raw bytes).
//
// During development the file may contain the all-zero placeholder; the
// launcher detects that and refuses to verify signatures (signature
// verification is bypassed in development mode only with the BR_DEV_SKIP_SIG
// env var).

pub const MANIFEST_PUBKEY: [u8; 32] =
    *include_bytes!("../../infrastructure/keys/manifest_pub.ed25519");

pub fn is_placeholder_key() -> bool {
    MANIFEST_PUBKEY.iter().all(|&b| b == 0)
}
